--BOOKING CURVES FOR MAY ONWARDS
--ADVANCED WORMS QUERY RBK

SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2026-05-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2026-04-01' AS PERIOD_START,
DATE '2026-04-30' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A 
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
--AND YM_TEAM_NM IN ('TRANSATLANTIC','TRANSPACIFIC','OTHER ATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) IN ('EDIJFK','EDIPHL','DELJFK','MIAMXP','JFKMXP','BUDPHL','ATHDFW','PHLPRG','MIAMXP','DFWZRH','NAPORD','JFKDEL','AMSPHL','ATHPHL','PHLZRH','JFKMXP')
GROUP BY 1,2,3,4,5,6,7,8

UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2026-06-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2026-05-01' AS PERIOD_START,
DATE '2026-05-31' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
--AND YM_TEAM_NM IN ('TRANSATLANTIC','TRANSPACIFIC','OTHER ATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND LEG_NON_DIRECTN_AIRPRT_IATA_CD IN ('EDIJFK','EDIPHL','DELJFK','MIAMXP','JFKMXP','BUDPHL','ATHDFW','PHLPRG','MIAMXP','DFWZRH','NAPORD','JFKDEL','AMSPHL','ATHPHL','PHLZRH','JFKMXP')
GROUP BY 1,2,3,4,5,6,7,8

UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2026-07-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2026-06-01' AS PERIOD_START,
DATE '2026-06-30' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
--AND YM_TEAM_NM IN ('TRANSATLANTIC','TRANSPACIFIC','OTHER ATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND LEG_NON_DIRECTN_AIRPRT_IATA_CD IN ('EDIJFK','EDIPHL','DELJFK','MIAMXP','JFKMXP','BUDPHL','ATHDFW','PHLPRG','MIAMXP','DFWZRH','NAPORD','JFKDEL','AMSPHL','ATHPHL','PHLZRH','JFKMXP')
GROUP BY 1,2,3,4,5,6,7,8

UNION
--BOOKING CURVE FOR PROXY 2025 START
--DELJFK, NAPORD
--ADVANCED WORMS QUERY RBK
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2025-06-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2025-05-01' AS PERIOD_START,
DATE '2025-05-31' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
--AND YM_TEAM_NM IN ('TRANSATLANTIC','TRANSPACIFIC','OTHER ATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) IN ('DELJFK','NAPORD')
GROUP BY 1,2,3,4,5,6,7,8
UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2025-07-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2025-06-01' AS PERIOD_START,
DATE '2025-06-30' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
--AND YM_TEAM_NM IN ('TRANSATLANTIC','TRANSPACIFIC','OTHER ATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) IN ('DELJFK','NAPORD')
GROUP BY 1,2,3,4,5,6,7,8
UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2025-08-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2025-07-01' AS PERIOD_START,
DATE '2025-07-31' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
--AND YM_TEAM_NM IN ('TRANSATLANTIC','TRANSPACIFIC','OTHER ATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) IN ('DELJFK','NAPORD')
GROUP BY 1,2,3,4,5,6,7,8

UNION
-- BOOKING CURVE JFKTLV23'
--ADVANCED WORMS QUERY RBK
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2023-08-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2023-07-01' AS PERIOD_START,
DATE '2023-07-31' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
AND YM_TEAM_NM IN ('TRANSATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) ='JFKTLV'
GROUP BY 1,2,3,4,5,6,7,8

UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2023-09-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2023-08-01' AS PERIOD_START,
DATE '2023-08-31' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
AND YM_TEAM_NM IN ('TRANSATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) ='JFKTLV'
GROUP BY 1,2,3,4,5,6,7,8

UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2023-10-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2023-09-01' AS PERIOD_START,
DATE '2023-09-30' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
AND YM_TEAM_NM IN ('TRANSATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) ='JFKTLV'
GROUP BY 1,2,3,4,5,6,7,8

UNION
-- BOOKING CURVE JFKTLV26'
--ADVANCED WORMS QUERY RBK
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2026-08-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2026-07-01' AS PERIOD_START,
DATE '2026-07-31' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,

MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
AND YM_TEAM_NM IN ('TRANSATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) ='JFKTLV'
GROUP BY 1,2,3,4,5,6,7,8

UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2026-09-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2026-08-01' AS PERIOD_START,
DATE '2026-08-31' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,
MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
AND YM_TEAM_NM IN ('TRANSATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) ='JFKTLV'
GROUP BY 1,2,3,4,5,6,7,8

UNION
SELECT 
'NORMAL' AS DATA_TYPE,
DATE '2026-10-01' AS END_OF_MONTH, --UPDATE EACH TIME WITH FIRST DAY OF NEXT MONTH!!!!!!!!
DATE '2026-09-01' AS PERIOD_START,
DATE '2026-09-30' AS PERIOD_END,
END_OF_MONTH  - (FILE_SNPSHT_DT) AS DAY_TO_END_OF_MONTH,

MONTH(LEG_DEP_DT) AS MTH,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NON_DIRECTN_AIRPRT_IATA_CD,
SLA_FACTOR,

SUM(CAB_TOT_PAX_QTY) AS PAX_QTY,
SUM(CAB_RPM_QTY) AS HELD_RPM,
SUM(CAB_ASM_QTY) AS HELD_ASM, 
SUM(CAB_TOT_REVNUE_AMT) AS BASE_YQ_REV,
SUM(CAB_AWD_MILE_EARN_REV_AMT) AS EARN_REV,
SUM(CAB_AWD_MILE_BURN_REV_AMT) AS BURN_REV,
SUM(CAB_INSTANT_UPSELL_REV_AMT) AS IU_REV,
SUM(CAB_IU_MILES_EARN_REV_AMT) AS IU_EARN_REV,
SUM(CAB_IU_MILES_BURN_REV_AMT) AS IU_BURN_REV
FROM PROD_RM_BUSINES_VW.RBK_LEG_CABIN_SUMRY_CURR A
LEFT JOIN 
    (SELECT LEFT(NONDIR_AIRPRT_PAIR_IATA_CD, 6) AS ALPHA,
    AVERAGE(STAGE_LENGTH_ADJUST_MLTPLR_QTY) AS SLA_FACTOR 
    FROM PROD_REFERENCE_DATA_VWS.STAGE_LENGTH_ADJ_AIRPRT_PAIR
    GROUP BY 1    ) SLA
    ON TRIM(A.LEG_NON_DIRECTN_AIRPRT_IATA_CD) = SLA.ALPHA
WHERE 1=1 
AND DAY_TO_END_OF_MONTH BETWEEN 0 AND 210
AND YM_TEAM_NM IN ('TRANSATLANTIC')
AND ((LEG_DEP_DT BETWEEN PERIOD_START AND PERIOD_END))
AND TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) ='JFKTLV'
GROUP BY 1,2,3,4,5,6,7,8
