SELECT
FILE_SNPSHT_DT AS SNAPSHOT_DATE,
--TRUNC(LEG_DEP_DT,'MON') AS FLIGHT_FIRST_MONTH,
YEAR(LEG_DEP_DT) AS DEP_YEAR,
MONTH(LEG_DEP_DT) AS DEP_MONTH,

CASE       
        WHEN FILE_SNPSHT_DT=CURRENT_DATE-2 THEN 'TY'       
        ELSE 'LY'       
    END AS TYLY, 
OPERAT_AIRLN_TYPE_CD AS OP_CARRIER,
MKT_AIRLN_IATA_CD AS MKT_CARRIER,

CASE
    WHEN TRIM(CURR_RM_TACTCL_RPT_GROUP_DESC) = 'OTHER ATLANTIC' THEN YM_SPOKE_NM
    ELSE TRIM(CURR_RM_TACTCL_RPT_GROUP_DESC) END AS TAC_ENT,
TRIM(LEG_NON_DIRECTN_AIRPRT_IATA_CD) AS LEG_NDir,
TRIM(OD_NON_DIRECTN_AIRPRT_IATA_CD) AS OD_NDir,
--TRIM(YM_HUB_NM) AS YM_HUB_NM,
--TRIM(YM_SPOKE_NM) AS YM_SPOKE_NM,
--TRIM(YM_HUB_DIRECTN_CD) AS YM_HUB_DIRECTN_CD,
--TRIM(YM_SPOKE_CNTRY_CD) AS YM_SPOKE_CNTRY_CD,
TRIM(YM_TEAM_NM) AS YM_TEAM_NM,

CASE 
    WHEN OPERAT_FARE_CABIN_CD IS NULL THEN 'Y'  
    ELSE OPERAT_FARE_CABIN_CD END AS CABIN,

CASE 
    WHEN ORIGNL_BKG_SRC_CNTRY_CD IN ('US') THEN 'US'
    WHEN ORIGNL_BKG_SRC_CNTRY_CD IS NULL AND SLS.PHYS_CNTRY_CD IN ('US') THEN 'US'
    WHEN ORIGNL_BKG_SRC_CNTRY_CD IN ('ES') THEN 'ES'
    WHEN ORIGNL_BKG_SRC_CNTRY_CD IS NULL AND SLS.PHYS_CNTRY_CD IN ('ES') THEN 'ES'
    WHEN ORIGNL_BKG_SRC_CNTRY_CD IS NULL AND SLS.PHYS_CNTRY_CD NOT IN ('US') AND SLS.PHYS_CNTRY_CD IS NOT NULL THEN 'INTL'
    WHEN ORIGNL_BKG_SRC_CNTRY_CD IS NULL AND SLS.PHYS_CNTRY_CD IS NULL THEN 'UNKN'
    ELSE 'INTL'
END AS POS,

CASE    
    WHEN SLS.PRIME_CHANL_TYPE_CD IS NULL AND (M.BKG_SRC_CD IN ('AA.COM','RESERVATIONS') OR M.BEST_TRAVEL_AGY_OUTLET_ID = '0000000')  THEN 'DIRECT'
    WHEN SLS.DEDICATE_ARC_TYPE_CD =  'DEDICATED_TLS' AND SLS.GLOBAL_SLS_ACCT_ID = 'G000031' THEN 'TLS'
    WHEN SLS.DEDICATE_ARC_TYPE_CD =  'MANAGED_GOV' THEN 'GOV'
    WHEN SLS.PRIME_CHANL_TYPE_CD IS NULL THEN 'LEISURE'
    ELSE SLS.PRIME_CHANL_TYPE_CD END AS CHANNEL,                    

TRIP_TYPE_CD AS TRIP_TYPE_CONNEX,

SUM(COALESCE(ONBRD_PAX_QTY,0)) AS PAX,
--SUM(COALESCE(ONBRD_RPM_QTY,0)) AS RPM,
--SUM(COALESCE(AWD_MILE_EARN_REV_AMT,0)) AS EARN_REV,
--SUM(COALESCE(AWD_MILE_BURN_REV_AMT,0)) AS BURN_REV,
SUM(COALESCE(ONBRD_TOT_REVNUE_AMT,0)) AS CASH_REV


FROM    PROD_RM_BUSINES_VW.RBK_OD_FLOW_DETL_CURR M
        LEFT JOIN PROD_GENL_SLS_VW.SLS_CHANL_CURR SLS ON M.BEST_TRAVEL_AGY_OUTLET_ID = SLS.SLS_OUTLET_ID

WHERE ((FILE_SNPSHT_DT IN CURRENT_DATE-2  AND LEG_DEP_DT > CURRENT_DATE-2 )                                                                     
        OR (FILE_SNPSHT_DT IN CURRENT_DATE-366 AND LEG_DEP_DT > CURRENT_DATE-366))                                
        
AND (LEG_DEP_DT > CURRENT_DATE-2
    OR LEG_DEP_DT > CURRENT_DATE-366)
AND TAC_ENT IN 'SPAIN'
AND OPERAT_AIRLN_IATA_CD  ='AA'       
AND YM_TEAM_NM = 'TRANSATLANTIC'  -- LIMITED TO TA TEAM; INCLUDE DOH, DEL & TLV
AND OPERAT_AIRLN_TYPE_CD IN ('M','R') -- LIMITED TO AA OPERATED FLIGHTS

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14
ORDER BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14
